# Allow CLI to work
ctrl_interface=/run/hostapd
ctrl_interface_group=0
# physical device (part of VLAN-aware bridge)
interface=radio3
driver=nl80211
# Set allowed frequency ranges and transmit power levels
country_code=DE
ieee80211d=1
# Band: a = 5GHz & 6GHz (a/n/ac/ax), g = 2Ghz (b/g/n)
hw_mode=g
channel=11
ieee80211n=1
macaddr_acl=0
# adapter/driver capabilities (iw list)
ht_capab=[SHORT-GI-20]
wmm_enabled=1
ignore_broadcast_ssid=0
ap_isolate=1
logger_syslog_level=4
### Guest SSID
ssid=ap.guest.home.arpa
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=YOUR_SECRET_PASSWORD
