#!/usr/bin/env dotnet

#:package ConsoleAppFramework@5.7.13
#:property TargetFramework=net10.0
#:property PublishAot=true
#:property PublishTrimmed=true
#:property OptimizationPreference=speed

using System.Text;
using System.Text.RegularExpressions;
using ConsoleAppFramework;

var app = ConsoleApp.Create();
app.Add<Commands>();
await app.RunAsync(args);

internal partial class Commands
{
    private static readonly Encoding Utf8NoBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: false);

    /// <summary>
    /// Reads an interfaces.conf template and generates the corresponding interfaces file.
    /// </summary>
    /// <param name="inputFile">Input interfaces.conf file.</param>
    /// <param name="outputFile">Output interfaces file. Defaults to ./interfaces.</param>
    [Command("")]
    public async Task ConvertAsync([Argument] string inputFile, [Argument] string outputFile = "interfaces", CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(inputFile);

        string[] lines = await File.ReadAllLinesAsync(inputFile, Utf8NoBom, cancellationToken);

        Dictionary<string, string> variables = new(StringComparer.Ordinal);
        HashSet<string> usedVariables = new(StringComparer.Ordinal);

        List<string> outputLines =
        [
            "# This file was generated using interfaces-conf.cs from a configuration file.",
            "# Do not edit this file directly, edit the configuration file instead.",
            "",
        ];

        foreach (string line in lines)
        {
            Match definitionMatch = DefinitionRegex.Match(line);
            if (definitionMatch.Success)
            {
                string key = definitionMatch.Groups["key"].Value;
                string value = definitionMatch.Groups["value"].Value;

                if (variables.ContainsKey(key))
                {
                    Console.Error.WriteLine($"Warning: variable {key} is defined more than once; using the last definition");
                }

                variables[key] = value;
                continue;
            }

            string replacedLine = VariableReferenceRegex.Replace(line, match =>
            {
                string key = match.Groups["key"].Value;
                if (!variables.TryGetValue(key, out string? value))
                {
                    throw new UndefinedVariableException(key);
                }

                usedVariables.Add(key);
                return value;
            });

            outputLines.Add(replacedLine);
        }

        foreach (string unusedVariable in variables.Keys.Except(usedVariables, StringComparer.Ordinal).Order(StringComparer.Ordinal))
        {
            Console.Error.WriteLine($"Warning: variable {unusedVariable} is defined but not used");
        }

        await File.WriteAllLinesAsync(outputFile, outputLines, Utf8NoBom, cancellationToken);
    }

    [GeneratedRegex(@"^\s*\$(define|DEFINE)\s+(?<key>_\w+)\s+(?<value>\w+)\s*(#.*)?$", RegexOptions.CultureInvariant)]
    private static partial Regex DefinitionRegex { get; }

    [GeneratedRegex(@"\$\{(?<key>_\w+)\}", RegexOptions.CultureInvariant)]
    private static partial Regex VariableReferenceRegex { get; }

    private sealed class UndefinedVariableException(string variableName) : Exception
    {
        public string VariableName => variableName;
    }
}
